### ISSUE TITLE
updateMain.bash script failing

### ISSUE THREAD

**Issue by caewok** [DMsGuild201/Foundry_Resources#7]
When I run the Plutonium/updateMain.bash script, I get the following error:
`updateMain.bash: line 46: syntax error: unexpected "(" (expecting "}")`

The specific line 46 is:
`local i ver1=($1) ver2=($2)`

My bash knowledge is not good enough to discern if this is a problem with the script or a problem with my setup. Looks like this code was added recently to the script. Thanks!

**Comment by TheTercept** [comment]
Can you give me the operating environment?

On Linux, in a terminal the `uname -a` command and `bash --version` output?

Also, how are you running the script.  It has been tested quite well and I'm not able to replicate this issue.  A full breakdown on what and how you are doing things will be appreciated.

**Comment by caewok** [comment]
Foundry is running on a local server in Docker. The uname output from within the docker container is below.
```
uname -a
Linux f0ca7cefded0 4.15.0-118-generic #119-Ubuntu SMP Tue Sep 8 12:30:01 UTC 2020 x86_64 Linux
```
But the docker container did not install bash, so I think it is falling back on sh. Would that script run differently under sh? 
[This is the docker image I am using.](https://github.com/felddy/foundryvtt-docker)

**Comment by TheTercept** [comment]
> 
> 
> Foundry is running on a local server in Docker. The uname output from within the docker container is below.
> 
> ```
> uname -a
> Linux f0ca7cefded0 4.15.0-118-generic #119-Ubuntu SMP Tue Sep 8 12:30:01 UTC 2020 x86_64 Linux
> ```
> 
> But the docker container did not install bash, so I think it is falling back on sh. Would that script run differently under sh?
> [This is the docker image I am using.](https://github.com/felddy/foundryvtt-docker)

Yes, you need BASH to use the script.  There is a Docker image that has the backend modded already which is available on wiki.5e.tools.  Use that.
